urls.py
from django.urls import path
from . import views

app_name = 'recette'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:recette_id>/', views.detail, name='detail'),
    path('ajout_recette', views.ajout_recette, name='ajout_recette'),
    path('<int:recette_id>/ajout_ingredient', views.ajout_ingredient, name='ajout_ingredient'),
    path('<int:ingredient_id>/supprimer_ingredient/', views.supprimer_ingredient, name='supprimer_ingredient'),
    path('<int:commentaire_id>/supprimer_commentaire/', views.supprimer_commentaire, name='supprimer_commentaire'),
    path('<int:recette_id>/modifier_recette', views.modifier_recette, name='modifier_recette'),
    path('<int:recette_id>/ajout_commentaire', views.ajout_commentaire, name='ajout_commentaire'),
]

models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import URLValidator
from django.utils.translation import gettext_lazy as _


# Create your models here.
def recette_directory_path(instance, filename):
    # MEDIA_ROOT/recette_<id>/<filename>
    return 'recette/_{0}/{1}'.format(instance.recette.id, filename)


class Cuisson(models.Model):
    nom = models.CharField(max_length=30)

    def __str__(self):
        return self.nom


class Type(models.Model):
    nom = models.CharField(max_length=30)

    def __str__(self):
        return self.nom


class Particularite(models.Model):
    nom = models.CharField(max_length=30)

    def __str__(self):
        return self.nom


class Recette(models.Model):
    class NiveauDeDifficulte(models.TextChoices):
        FACILE = 'F', _('Facile')
        MOYEN = 'M', _('Moyen')
        DIFFICILE = 'D', _('Difficile')

    class NiveauDeCout(models.TextChoices):
        FAIBLE = 'F', _('Faible')
        MOYEN = 'M', _('Moyen')
        ELEVE = 'E', _('Eleve')

    titre = models.CharField(max_length=255)
    description = models.TextField()
    nombre_visite = models.IntegerField(default=0)
    nombre_mangeur = models.IntegerField(default=0)
    difficulte = models.CharField(max_length=1,
                                  choices=NiveauDeDifficulte.choices,
                                  default=NiveauDeDifficulte.FACILE)
    cout = models.CharField(max_length=1,
                            choices=NiveauDeCout.choices,
                            default=NiveauDeCout.MOYEN)
    calorie = models.IntegerField(default=0)
    temps_preparation = models.IntegerField()
    temps_cuisson = models.IntegerField(default=0)
    temps_repos = models.IntegerField(default=0)
    ustensile = models.CharField(max_length=255)
    cree = models.DateTimeField(auto_now_add=True)
    maj = models.DateTimeField(auto_now=True)
    cuisson = models.ForeignKey(Cuisson, on_delete=models.CASCADE)
    type = models.ForeignKey(Type, on_delete=models.CASCADE)
    particularite = models.ForeignKey(Particularite, on_delete=models.CASCADE)
    utilisateur = models.ForeignKey(User, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.titre


class Ingredient(models.Model):
    designation = models.CharField(max_length=255)
    quantite = models.DecimalField(max_digits=7, decimal_places=1)
    ordre = models.IntegerField(default=0)
    recette = models.ForeignKey(Recette, on_delete=models.CASCADE)

    def __str__(self):
        return self.designation


class Media(models.Model):
    photo = models.ImageField(upload_to=recette_directory_path)
    url = models.CharField(max_length=255, validators=[URLValidator])
    recette = models.ForeignKey(Recette, on_delete=models.CASCADE)

    def __str__(self):
        return self.url


class Commentaire(models.Model):
    description = models.TextField()
    cree = models.DateTimeField(auto_now_add=True)
    maj = models.DateTimeField(auto_now=True)
    recette = models.ForeignKey(Recette, on_delete=models.CASCADE)
    utilisateur = models.ForeignKey(User, default=1, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.cree)

templates/recette/ajout_ingredient.html
{% extends 'recette/base.html' %}
{% block contenu %}
{% load static %}

<div class="wrap full-wrap">
    <h1 class="entry-title">
        <a href="{% url 'recette:detail' recette.id %}">
            <img src="{% static 'recette/images/icons/retour.png' %}" title="Revenir en arrière" />
        </a>
    Ajouter des ingrédients pour {{ recette.titre }}
    </h1>
    <div class="main-wrap">
        <div class="loop">
            <div class="inner">
                <form action="{% url 'recette:ajout_ingredient' recette.id %}" id="addIngre" class="searchform" method="post">
                    {% csrf_token %}
                    {% for formIngredient in liste_formulaire_ingredient %}
                    {{ formIngredient.as_p }}
                    {% endfor %}
                    {{ liste_formulaire_ingredient.management_form }}
                    <input type="submit" name="ajouter" value="ajouter">
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/recette/ajout_recette.html
{% extends 'recette/base.html' %}
{% block contenu %}
{% load static %}

<div class="wrap full-wrap">
    <h1 class="entry-title">
    Ajouter une recette
    </h1>
    <div class="main-wrap">
        <div class="loop">
            <div class="inner">
                <form action="{% url 'recette:ajout_recette' %}" enctype="multipart/form-data" class="searchform" method="post">
                    {% csrf_token %}
                    {{ recette_formset.as_p }}
                    {{ media_formset.as_p }}
                    <input type="submit" value="ajouter">
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/recette/base.html
<!doctype html>
<html class="home blog no-js" lang="fr-FR">
<head>
    <title>Recettes</title>
{% load static %}
    <meta charset="UTF-8"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          type="text/css" media="all"/>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Amatic+SC%3A400%2C700%7CLato%3A400%2C700%2C400italic%2C700italic&amp;ver=4.9.8"
          type="text/css" media="screen"/>
    <link rel="stylesheet" href="{% static 'recette/css/style.css' %}" type="text/css" media="screen"/>
    <link rel="stylesheet" href="{% static 'recette/css/print.css' %}" type="text/css" media="print"/>
    <!--[if (lt IE 9) & (!IEMobile)]>
    <link rel="stylesheet" id="lt-ie9-css" href="{% static 'recette/css/ie.css' %}" type="text/css" media="screen"/>
    <![endif]-->
    <script src="{% static 'recette/js/jquery-3.0.0.min.js' %}"></script>
    <script src="{% static 'recette/js/jquery-migrate-3.0.1.min.js' %}"></script>
    <script src="{% static 'recette/js/recette.js' %}"></script>

</head>
<body class="home sticky-menu sidebar-off" id="top">

<header class="header">

    <div class="header-wrap">

        <div class="logo plain logo-left">
            <div class="site-title">
                <a href="{% url 'recette:index' %}" title="Revenir à la page d'accueil">Recettes</a>
            </div>
        </div><!-- /logo -->

        <nav id="nav" role="navigation">
            <div class="table">
                <div class="table-cell">
                    <ul id="menu-menu-1">
                        <li class="menu-item">
                            <a href="{% url 'recette:index' %}">Accueil</a></li>
                        <li class="menu-item">
                            <a href="{% url 'recette:ajout_recette' %}">Ajouter une recette</a></li>
                        <li class="menu-item">
                            {% if user.is_authenticated %}
                            <a href="{% url 'admin:logout' %}?next=/recette/" title="Se déconnecter">
                                {{ user.get_username }}
                            </a>
                            {% else %}
                            <a href="{% url 'admin:login' %}?next=/recette/">Se connecter</a>
                            {% endif %}
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <a href="#nav" class="menu-trigger"><i class="fa fa-bars"></i></a>

        <a href="#topsearch" class="search-trigger"><i class="fa fa-search"></i></a>

    </div>

</header>

{% block contenu %}
{% endblock %}

<div id="topsearch">
    <div class="table">
        <div class="table-cell">
            <form role="search" method="post" class="searchform" action="{% url 'recette:index' %}">
                <div>
                    {% csrf_token %}
                    <input type="text" value="" name="s" class="s" placeholder="Votre recherche"/>
                    <input type="submit" class="searchsubmit" value="Search"/>
                </div>
            </form>
        </div>
    </div>
    <a href="#topsearch" class="search-trigger"><i class="fa fa-times"></i></a>
</div>

<div class="footer-widgets widget-count-4">

    <div class="wrap">

        <div class="mt-about-you-widget">
            <div class="widget footer">

                <img class="mt-about-avatar" src="{% static 'recette/images/quisuisje.jpg' %}" alt="Nana"/>


                <h4>Nana</h4>

                <div class="mt-about-bio">
                    <p>Pendant le grand confinement, mon mari et mon fils ainé se
                    sont mis à coder ce petit espace pour mes recettes en python avec Django...</p>
                </div>


            </div>
        </div>
        <div class="widget footer"><h4>Dernières recettes</h4>
            <ul>
                {% for recette in aff_footer %}
                <li>
                    <a href="{% url 'recette:detail' recette.id %}">{{ recette.titre }}</a>
                </li>
                {% endfor %}
            </ul>
        </div>
        <div class="widget footer"><h4>Categories</h4>
            <ul>
                <li class="cat-item cat-item-6">
                    <a href="#" title="A cute little description would go in here">Blog</a>
                </li>
                <li class="cat-item cat-item-7">
                    <a href="#" title="A cute little description would go in here">Cute</a>
                </li>
                <li class="cat-item cat-item-8">
                    <a href="#">Fitness</a>
                </li>
                <li class="cat-item cat-item-9">
                    <a href="#">Fun</a>
                </li>
            </ul>
        </div>
        <div class="widget footer"><h4>Gallery</h4>
            <div class="textwidget">
                <img src="{% static 'recette/images/icons/social-dribbble-black@2x.png' %}" alt="">
            </div>
        </div>
    </div>

</div>

<footer class="footer">
    <div class="footer-wrap">
        <div id="footer-text">&copy; 2018 Itsy.
            Réalisé par <a href="https://freehtml5.co" target="_blank">FreeHTML5</a>. Merci à eux.
        </div>
        <a href="#content">Recettes <i class="fa fa-chevron-up"></i></a> -
        <a href="#top" id="btt">Haut <i class="fa fa-chevron-up"></i></a>
    </div>
</footer>
<script>var ie9 = false;</script>
<!--[if lte IE 9 ]>
<script> var ie9 = true; </script>
<![endif]-->
<script src="{% static 'recette/js/global-plugins.min.js' %}"></script>
<script src="{% static 'recette/js/main.js' %}"></script>
</body>
</html>

templates/recette/detail.html
{% extends 'recette/base.html' %}
{% block contenu %}
{% load static %}

<div class="wrap full-wrap">
    <div class="main-wrap">
        <section class="main main-archive">
            <div class="loop">
                <article class="post format-image has-post-thumbnail post_format-post-format-image">

  		            <span class="post-image">
  			  				<a href="#" title="{{ recette.titre }}">
                                {% for media in recette.media_set.all %}
  			  				    <img width="916" height="611" src="{{ media.photo.url }}"
                                     class="attachment-desktop size-desktop" alt="{{ recette.titre }}"/>
                                {% endfor %}
                            </a>

  		            </span>

                    <div class="inner">

                        <h2 class="entry-title">
                            {% if user.is_authenticated %}
                            <a href="{% url 'recette:modifier_recette' recette.id %}" title="Cliquez pour modifier la recette">
                            {% else %}
                            <a href="#" title="{{ recette.titre }}">
                            {% endif %}
                                {{ recette.titre }}
                            </a>
                        </h2>
                        <ul class="meta top">
                            <li class="time">
                                <a href="#"
                                   title="Mise à jour le {{ recette.maj|date:'d/m/Y' }}">
                                    <time class="post-date updated" datetime="{{ recette.cree|date:'Y-m-d' }}">
                                        {{ recette.cree|date:'d/m/Y' }}
                                    </time>
                                </a>
                            </li>

                            <li class="comments post-tags">
                                <a href="#comments" title="Voir les commentaires">
                                    {{ recette.commentaire_set.count }} commentaire{{ recette.commentaire_set.count|pluralize }}
                                </a>
                            </li>

                            <li class="author-m post-tags">
                                Par
                                <span class="vcard author post-author">
                                    <span class="fn">
                                        <a href="#" title="Posts by {{ recette.utilisateur }}" rel="author">
                                    {{ recette.utilisateur }}
                                        </a>
                                    </span>
                                </span>
                            </li>

                        </ul>
                        <div class="post-content">
                            <p style="text-align: center;">
                                Préparation {{ recette.temps_preparation }} mn
                                | <span title="{{ recette.cuisson }}">Cuisson {{ recette.temps_cuisson }} mn</span>
                                | Difficulté {{ recette.get_difficulte_display }}
                                | Coût {{ recette.get_cout_display }}
                            </p>
                            <blockquote class="content-quote" id="liste_ingredients">
                                {% if user.is_authenticated %}
                                <a href="{% url 'recette:ajout_ingredient' recette.id %}" title="Modifier la liste des ingrédients">
                                    Ingrédients
                                </a>
                                {% else %}
                                Ingrédients
                                {% endif %}
                                pour {{ recette.nombre_mangeur }} mangeurs
                                        <ul>
                                            {% for ing in recette.ingredient_set.all %}
                                            {% if user.is_authenticated %}
                                            <li value="{{ ing.id }}" title="Cliquer pour supprimer l'ingrédient">[-]
                                            {% else %}
                                            <li value="0">
                                            {% endif %}
                                                {{ ing.quantite }} {{ ing.designation }}
                                            </li>
                                            {% endfor %}
                                        </ul>
                            </blockquote>
                            {{ recette.description|linebreaks }}
                        </div>



                        <ul class="meta bottom">

                            <li class="cat post-tags">Saved:
                                <a href="#" title="Type de recette">{{ recette.type }}</a>,
                                <a href="#" title="Mode de cuisson">{{ recette.cuisson }}</a>,
                                <a href="#" title="Particularité">{{ recette.particularite }}</a>
                            </li>

                        </ul>
                    </div>
                    <div id="comments">
                        <h5 id="respond">Commentaires...</h5>
                        <div class="commentlist">
                            <ul class="comments-wrapper" style="background: rgba(250, 250, 250);">
                                {% for com in recette.commentaire_set.all %}
                                <li>
                                    <div class="comment-body">
                                        {{ com.description|linebreaks }}
                                    </div>
                                    <p class="comment-date">
                                        Ecrit le {{ com.maj|date:'d/m/Y' }} par {{ com.utilisateur }}
                                        {% if user.is_authenticated %}
                                            {% if user.id == com.utilisateur_id %}
                                         <span class="suppr" data-id="{{ com.id }}">[X]</span>
                                            {% endif %}
                                        {% endif %}
                                    </p>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    {% if user.is_authenticated %}
                    <div>
                        <form action="{% url 'recette:ajout_commentaire' recette.id %}" method="post">
                            {% csrf_token %}
                            {{ commentaire_form.as_p }}
                            <input type="submit" name="ajouter" value="Ajouter" />
                        </form>
                    </div>
                    {% endif %}
                </article>
            </div>
        </section>
    </div>
</div>

{% endblock %}

templates/recette/index.html
{% extends 'recette/base.html' %}
{% block contenu %}
{% load static %}

<div class="hero" style="background-image: url('{% static 'recette/images/lead2.jpg' %}'); text-align:right;">
    <div class="hero-inner">
        <div class="inner">
            <h1><span class="border border-top border-bottom">Nana</span></h1>
            <div class="hero-line-one"></div>
            <div class="hero-line-two">
                <span class="border border-bottom">
                    <a href="#" style="color:#FFF;">
                        cuisine
                    </a>
                </span>
            </div>
        </div>

        <a class="more-arrow" href="#content"><i class="fa fa-chevron-down"></i><span>Scroll Down</span></a>

    </div>
</div>
<div class="home-sticky" id="content">

    <h2 class="home-sticky-title">Mes recettes</h2>

    <div class="sticky-inner">
    {% for recette in page_obj %}
        <aside class="home-sticky-post post has-post-thumbnail sticky">

  		    <span class="post-image">
  				<a href="{% url 'recette:detail' recette.id %}">
            {% for media in recette.media_set.all %}
                <img width="502" height="502" src="{{ media.photo.url }}"
                     class="attachment-sticky size-sticky" alt=""/>
            {% endfor %}
  				</a>
  		    </span>

            <div class="inner">
                <h3 class="entry-title">
                    <a href="#">{{ recette.titre }}</a>
                </h3>

                <ul class="meta top">
                    <li class="time">
                        <a href="#">
                            <time class="post-date updated" datetime="2015-02-02">{{ recette.cree }}</time>
                        </a>
                    </li>
                </ul>
            </div>

        </aside>
    {% endfor %}

    </div>
    <div class="pagination">
        <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">Début</a> -
            <a href="?page={{ page_obj.previous_page_number }}">Précédente</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} sur {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Suivante</a> -
            <a href="?page={{ page_obj.paginator.num_pages }}">Dernière</a>
        {% endif %}
        </span>
    </div>
</div>


{% endblock %}

templates/recette/modifier_recette.html
{% extends 'recette/base.html' %}
{% block contenu %}
{% load static %}


<div class="wrap full-wrap">
    <h1 class="entry-title">
    Modifier une recette
    </h1>
    <div class="main-wrap">
        <div class="loop">
            <div class="inner">
                <form action="{% url 'recette:modifier_recette' recette.id %}" enctype="multipart/form-data" class="searchform" method="post">
                    {% csrf_token %}
                    {{ recette_formset.as_p }}

                    <input type="submit" value="ajouter">
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}